[kaonic-plugin]
name = "Kaonic Sample Plugin"
description = "Reference plugin package used to prototype installer-side plugin lifecycle management."
version = "0.1.0"
service = "kaonic-plugin-sample.service"
developer = "Beechat Network Systems Ltd"
channel = "experimental"
icon = "icon.svg"
github_url = "https://github.com/BeechatNetworkSystemsLtd/kaonic-gateway"
symlink = "/usr/bin/kaonic-plugin-sample"
